logging:
   file:
      name: logs/application.log
spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hibernate_sample?useSSL=false&serverTimezone=UTC
      username: root
      password: null
   jpa:
      hibernate:
         ddl-auto: update
      generate-ddl: true
      show-sql: true
      properties:
         hibernate:
            cache:
               use_query_cache: true
               use_second_level_cache: true
               provider_class: org.hibernate.cache.EhCacheProvider
               region:
                  factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
            generate_statistics: true
         javax:
            persistence:
               sharedCache:
                  mode: ENABLE_SELECTIVE
   cache:
      ehcache:
         config: classpath:ehcache.xml  L
   jackson:
      serialization:
         fail-on-empty-beans: false
security:
   jwt:
      token:
         secret-key: secret
      expire-length: 3600000
server:
   port: 8085
   session-timeout: 30